# cloud-config
users:
    - name: ${user_name}
      groups: sudo
      shell: /bin/bash
      sudo: ALL=(ALL) NOPASSWD:ALL
      ssh_authorized_keys:
        - ${ssh_public_key}

package_update: true
package_upgrade: true
packages:
    - postgresql
    - postgresql-contrib
    - redis-server
    - git
    - gpg
    - gnupg2
    - rsync

write_files:
- encoding: b64
  content: ${ssh_ca_public_key}
  owner: root:root
  path: /etc/ssh/ca.pub
  permissions: '644'
- encoding: b64
  content: ${cloudflared_config}
  owner: root:root
  path: /etc/cloudflared/config.yml
  permissions: '644'
- encoding: b64
  content: ${cloudflared_auth}
  owner: root:root
  path: /etc/cloudflared/${argo_tunnel_id}.json
  permissions: '644'
- encoding: b64
  content: ${laptop}
  owner: ${user_name}:${user_name}
  path: /home/${user_name}/laptop
  permissions: '775'

bootcmd:
  - echo '127.0.0.1 ${hostname}' >> /etc/hosts
  - echo '127.0.0.1 ${domain}' >> /etc/hosts

runcmd:
    # Configure SSH for short-lived ca
    - sudo sh -c 'echo "PubkeyAuthentication yes" >> /etc/ssh/sshd_config'
    - sudo sh -c 'echo "TrustedUserCAKeys /etc/ssh/ca.pub" >> /etc/ssh/sshd_config'
    - sudo systemctl restart ssh
